use serde::Deserialize;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Deserialize, Default)]
#[serde(default)]
pub struct Config {
    pub theme: Option<String>,
    pub frontmatter: Option<bool>,
    pub runcmd: Option<String>,
    pub sidetoc_width: Option<u32>,
    pub sidetoc_position: Option<String>,
    pub keybindings: Option<std::collections::HashMap<String, String>>,
}

impl Config {
    /// Load config from the default XDG path.
    pub fn load() -> Config {
        let path = config_path();
        Self::load_from(&path)
    }

    /// Load config from a TOML string. Returns defaults if malformed.
    pub fn load_from_str(content: &str) -> Config {
        match toml::from_str::<Config>(content) {
            Ok(config) => config,
            Err(_) => Config::default(),
        }
    }

    /// Load config from an explicit path. Returns defaults if the file
    /// is missing or malformed.
    pub fn load_from(path: &Path) -> Config {
        let content = match fs::read_to_string(path) {
            Ok(c) => c,
            Err(_) => return Config::default(),
        };

        match toml::from_str::<Config>(&content) {
            Ok(config) => {
                if let Some(ref theme) = config.theme {
                    if !["system", "light", "dark"].contains(&theme.as_str()) {
                        eprintln!("warning: invalid theme '{}' in config, using default", theme);
                        return Config {
                            theme: None,
                            ..config
                        };
                    }
                }
                if let Some(ref pos) = config.sidetoc_position {
                    if !["left", "right"].contains(&pos.as_str()) {
                        eprintln!("warning: invalid sidetoc_position '{}' in config, using default", pos);
                        return Config {
                            sidetoc_position: None,
                            ..config
                        };
                    }
                }
                config
            }
            Err(e) => {
                eprintln!("warning: invalid config file: {}", e);
                Config::default()
            }
        }
    }

    pub fn theme(&self) -> &str {
        self.theme.as_deref().unwrap_or("system")
    }

    pub fn frontmatter(&self) -> bool {
        self.frontmatter.unwrap_or(false)
    }

    pub fn runcmd(&self) -> Option<&str> {
        self.runcmd.as_deref()
    }

    pub fn sidetoc_width(&self) -> u32 {
        self.sidetoc_width.unwrap_or(250)
    }

    pub fn sidetoc_position(&self) -> &str {
        self.sidetoc_position.as_deref().unwrap_or("left")
    }
}

/// Returns the documented default config template.
pub fn default_config_template() -> &'static str {
    r#"# mip configuration
# Generated by: mip --initconf

# Color theme: "system", "light", or "dark"
# "system" follows your desktop's dark/light preference
theme = "system"

# Show YAML frontmatter as a table above the content
frontmatter = false

# Command(s) to run at startup (semicolon-separated)
# Examples:
#   runcmd = "sidetoc_open"
#   runcmd = "sidetoc_open; set theme dark"
# runcmd = ""

# Side table of contents panel width in pixels
sidetoc_width = 250

# Side table of contents position: "left" or "right"
sidetoc_position = "left"

# Keybindings: key_combo = "command"
# Key combos: ctrl+key, shift+key, alt+key, super+key, or plain key
# Commands can be composed with semicolons: "cmd1; cmd2"
#
# Available commands:
#   q / close              - quit mip
#   open <path> / o <path> - open a markdown file
#   print                  - open print dialog (Ctrl+P)
#   quicktoc               - toggle fullscreen TOC overlay
#   sidetoc_open           - show side TOC panel
#   sidetoc_close          - hide side TOC panel
#   sidetoc_toggle         - toggle side TOC panel
#   sidetoc_expand_width   - widen side TOC panel
#   sidetoc_shrink_width   - narrow side TOC panel
[keybindings]
tab = "quicktoc"
"ctrl+p" = "print"
# "ctrl+b" = "sidetoc_toggle"
# "ctrl+y" = "open ~/todo.md"
"#
}

pub fn config_path() -> PathBuf {
    let config_dir = std::env::var("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
            PathBuf::from(home).join(".config")
        });
    config_dir.join("miprs").join("config.toml")
}
